sudo: true
language: java
jdk:
  - oraclejdk8

# install node and gitbook globally
before_install:
  - npm install -g gitbook-cli
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

# build limes
install:
  - sudo add-apt-repository -y ppa:webupd8team/java
  - sudo apt-get update

  - sudo apt-get install -y oracle-java8-installer || true

  #todo remove this kludge and the above || true when the ppa is fixed
  - pushd /var/lib/dpkg/info
  - sudo sed -i 's|JAVA_VERSION=8u161|JAVA_VERSION=8u172|' oracle-java8-installer.*
  - sudo sed -i 's|PARTNER_URL=http://download.oracle.com/otn-pub/java/jdk/8u161-b12/2f38c3b165be4555a1fa6e98c45e0808/|PARTNER_URL=http://download.oracle.com/otn-pub/java/jdk/8u172-b11/a58eab1ec242421181065cdc37240b08/|' oracle-java8-installer.*
  - sudo sed -i 's|SHA256SUM_TGZ="6dbc56a0e3310b69e91bb64db63a485bd7b6a8083f08e48047276380a0e2021e"|SHA256SUM_TGZ="28a00b9400b6913563553e09e8024c286b506d8523334c93ddec6c9ec7e9d346"|' oracle-java8-installer.*
  - sudo sed -i 's|J_DIR=jdk1.8.0_161|J_DIR=jdk1.8.0_172|' oracle-java8-installer.*
  - popd
  - sudo apt-get update

  - sudo apt-get install -y oracle-java8-installer
  - mvn install -U -Dmaven.test.skip=true

# execute tests
script:
  - mvn test

# deploy gitbook after success
after_success: bash ./gh-deploy.sh

# disable emails, enable slack push
notifications:
  email: false
  slack:
    secure: W641/UZMvWBySvE/TfBDgJSk5qjGWyf/ujDkDzMRr14tglUaEIwYcpOBXVodrziZDMg2zW+G/n5pO76JQGetdkgeHF7Rv3/aA9DQhGVq+MwatkYrxqqIfFqnp4Pa/gNUKYdPE8BicJI9f5NETc5rRCSesLFpLKHHopZQo24bY0Xve5E/8enPFSZ5Jqz3Bz/VIYSnMDt/xzyl0lLswRno1EFn8vGkNyh8ZV+uzSHx2Hng9G+4qgqVqrvjsIu8/fxvvKkBcMxebkG74JPoXl5CrxG9N6z/1BBYEpFHP9p2lWMHnAXh2jCkHjxkF+Y+k46BgAwqU6Pk/WYI9BKAKcaqgwJsIJHPk/YPMdYI/p9nKDHn99kfitL7Gfa7Wfy2edC0v9KlVemL6y/jAJF+r82tCWGvuON4irBkEUs8kBoIXuvH8yiG/LcfvuzTOIF5Kw3AknvGwSjeIiLx08vSFexQQWIL0cCLoCr5S8YNlQa4Hfux8O4J3itOBosOhy6A1RxYxigPFKojAJLzY5JSemab/8OnHSGjJ4DPGfG/xg+T1vrGcJ9ddQwPhqa+F0NKIMaTQ0ZcoFHVY1ZtDmCvyKiYaxLPQqDpTNGF9CmnCQTQGy+z3BHDYCgb8dh8VopMlYWKQ4kXuXJP4EVkGkoORxRLUaRB3BxHLOVoJmienKzH9EM=

env:
  global:
  - ENCRYPTION_LABEL: "eec107ffaeb8"
  - COMMIT_AUTHOR_EMAIL: "yamalight+travis@gmail.com"
